parameters:
    sonata.page.service.class: Awaresoft\Sonata\PageBundle\Page\PageServiceManager
    sonata.page.service.default.class: Awaresoft\Sonata\PageBundle\Page\Service\DefaultPageService
    sonata.page.transformer.class: Awaresoft\Sonata\PageBundle\Entity\Transformer

services:
    sonata.page.response_listener:
        class: Awaresoft\Sonata\PageBundle\Listener\ResponseListener
        scope: request
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onCoreResponse, priority: -1 }
        arguments:
            - "@sonata.page.cms_manager_selector"
            - "@sonata.page.page_service_manager"
            - "@sonata.page.decorator_strategy"
            - "@templating"
            - "@service_container"

    awaresoft.page.manager.page:
        class: Awaresoft\Sonata\PageBundle\Entity\PageManager
        arguments:
            - "%sonata.page.page.class%"
            - "@doctrine"
            - []
            - []
            - "@service_container"

    awaresoft.page.listener.controller:
        class: Awaresoft\Sonata\PageBundle\Listener\ControllerListener
        scope: request
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 0 }
        arguments:
            - "@sonata.page.cms_manager_selector"
            - "@sonata.page.page_service_manager"
            - "@sonata.seo.page.default"
            - "@awaresoft.setting"

    awaresoft.page.twig.shared_block_extension:
        class: Awaresoft\Sonata\PageBundle\Twig\SharedBlockExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, ["@service_container"]]