services:
    awaresoft.page.kernel.exception_listener:
        class: Awaresoft\Sonata\PageBundle\Listener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -125 }
        arguments:
            - "@service_container"