parameters:
    sonata.page.service.class: Awaresoft\Sonata\PageBundle\Page\PageServiceManager
    sonata.page.service.default.class: Awaresoft\Sonata\PageBundle\Page\Service\DefaultPageService
    sonata.page.transformer.class: Awaresoft\Sonata\PageBundle\Entity\Transformer
    sonata.page.route.page.generator.class: Awaresoft\Sonata\PageBundle\Route\RoutePageGenerator
    awaresoft.page.shared_block.disabled_block_list:
        - sonata.block.service.container
        - sonata.block.service.menu
        - sonata.page.block.container
        - sonata.page.block.shared_block
        - sonata.page.block.children_pages
        - awaresoft.breadcrumb.block.breadcrumb
        - awaresoft.dynamic_block.block.dynamic_block

services:
    sonata.page.response_listener:
        class: Awaresoft\Sonata\PageBundle\Listener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onCoreResponse, priority: -1 }
        arguments:
            - '@sonata.page.cms_manager_selector'
            - '@sonata.page.page_service_manager'
            - '@sonata.page.decorator_strategy'
            - '@templating'
            - '%sonata.page.skip_redirection%'
            - '@service_container'

    awaresoft.page.manager.page:
        class: Awaresoft\Sonata\PageBundle\Entity\PageManager
        arguments:
            - '%sonata.page.page.class%'
            - '@doctrine'
            - []
            - []
            - '@service_container'

    awaresoft.page.listener.controller:
        class: Awaresoft\Sonata\PageBundle\Listener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 0 }
        arguments:
            - '@sonata.page.cms_manager_selector'
            - '@sonata.page.page_service_manager'
            - '@sonata.seo.page.default'
            - '@awaresoft.setting'

    awaresoft.page.twig.shared_block_extension:
        class: Awaresoft\Sonata\PageBundle\Twig\SharedBlockExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, ['@service_container']]